### ISSUE TITLE
How to set metadata (migrating from Flask-SQLAlchemy)?

### ISSUE THREAD

**Issue by janpeterka** [miguelgrinberg/alchemical#11]
Sorry for possibly stupid question.  
I'm trying to migrate from `Flask-SQLAlchemy` (in hope of solving some errors, and also forcing me to use new querying syntax).

I was creating db this way: 
```python
db = SQLAlchemy(
    session_options={"autoflush": False},
    metadata=MetaData(naming_convention=convention),
)
```
and I'm not sure how to change this to Alchemical.  
Is it correct to change `session_options` to `engine_options`?
And how do I give my naming conventions somewhere for sqlalchemy to use?

Thank you for help!

**Comment by miguelgrinberg** [comment]
First of all and in case you don't know, you can use the new query syntax with Flask-SQLAlchemy (a recent one, of course). If that is the only reason you are switching, you don't have to.

Now regarding your questions. Unfortunately Alchemical is extremely opinionated, as it was born as a private thing that I only I used. I have been adding more general purpose options, but as it turns out, I have not made it possible yet to define session options. I will add that.

A custom metadata object is problematic, I'm not sure if I'll add that. Alchemical manages your metadata, and when/if necessary it creates multiple ones, such as when using multiple databases. I can add metadata options though. In any case, Alchemical initializes the widely accepted naming conventions in all the metadata object it creates, so you may not need to do this anymore if you switch.

**Comment by janpeterka** [comment]
Thanks for answering so swiftly!  

Well, main reason I started playing with this is that we are having constant random db connection errors in our app and we have no idea what's causing them, so we are trying anything that might help :sweat_smile: 
I also like your `Model.select()` syntax, as it's simpler than `db.select(User)` that Flask-SQLAlchemy uses. Im still not happy about new way of querying, as it's much longer and less readable (and using Rails in my job, it's really a striking difference between readability and developer ease). But after some trying, it seems like I will really stay with Flask-SQLAlchemy for now.

Having reasonable default naming conventions is great, I don'ŧ understand why these (taken from SQLAlchemy docs) are not default.
