### ISSUE TITLE
Documentation is not clear

### ISSUE THREAD

**Issue by NAN-CForadas** [miguelgrinberg/alchemical#6]
```text
session.scalars(query): Returns an iterable with a single result per row.
session.scalar(query): Returns the first result from the first row.
session.execute(query): Returns an iterable with a tuple of results per row.
```

Did you mean to say something like
'session.scalars(query).all(): Returns an iterable with a single result per row.'?

**Comment by miguelgrinberg** [comment]
The section of the docs you are reading has a link to the SQLAlchemy documentation, where you can find details about these methods. They are listed here just as a quick summary.

In any case, when you use the `session.scalars(query).all()` you get a list. When you use `session.scalars(query)` you get an iterable, which is a more generic type of sequence that is more efficient to iterate on, since results are obtained as you iterate.
